# Generated by Django 4.0.2 on 2022-02-13 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='profile',
        ),
    ]
